name: CI/CD Pipeline
on: [push]

jobs:
  compile-jar:
    runs-on: adoptopenjdk/openjdk8
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install tools
        run: apt update && apt install graphviz
      - name: Build
        run: bash util/plantuml.sh
      - name: Récupérer le diagramme
        uses: actions/upload-artifact@v2
        with:
          name: app
          path: *.png
